version: 0.2

phases:
  build:
    commands:  # E229UBUXBQ309W front id
      - aws cloudfront create-invalidation --distribution-id "E229UBUXBQ309W" --paths "/*"

artifacts:
  files: "**/*"
  exclude_buildspec: true